### ISSUE TITLE
Can't import module from python 3.11/3.12

### ISSUE THREAD

**Issue by Uinelj** [cosmograph-org/py_cosmograph#19]
Hey! Thank you for the library :) 

I've been trying to use this python wrapper without success: it seems there are some import failures.

Tested on a new venv, using `uv` and python `3.11` and `3.12`:

```
>>> import cosmograph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XX/dev/tmp/cosmotest/.venv/lib/python3.11/site-packages/cosmograph/__init__.py", line 4, in <module>
    from cosmograph.base import cosmo, base_cosmo
  File "/Users/XX/dev/tmp/cosmotest/.venv/lib/python3.11/site-packages/cosmograph/base.py", line 7, in <module>
    from cosmograph._resources import configs_dacc
  File "/Users/XX/dev/tmp/cosmotest/.venv/lib/python3.11/site-packages/cosmograph/_resources.py", line 1160, in <module>
    from ju import trait_to_py
ImportError: cannot import name 'trait_to_py' from 'ju' (/Users/XX/dev/tmp/cosmotest/.venv/lib/python3.11/site-packages/ju/__init__.py)
```

Is there anything I can help you with to diagnose this?

**Comment by thorwhalen** [comment]
Hi @Uinelj ! How did you even find this!?

I was doing a bunch of dev on `py_cosmograph`, preparing for our official "beta" release (today), oblivious to the fact that someone might actually be trying it before it was announced...

Try it now. It should work. 

And to boot, you have an actual readme and a few colab notebook examples to play with. 

Enjoy, and let us know if something doesn't work.
